server.port=8080
logging.level.org.zalando.logbook=TRACE
logging.level.ru.yandex.practicum.filmorate=DEBUG
logbook.strategy=default
spring.application.name=filmorate

spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:file:./db/filmorate;DATABASE_TO_UPPER=FALSE;MODE=PostgreSQL;AUTO_SERVER=TRUE;IFEXISTS=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console